name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push:
  workflow_dispatch: 

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - name: System Information
        run: |
          echo "OS Details:"
          cat /etc/os-release
          echo "--------------------------------"
          echo "CPU Info:"
          lscpu
          echo "--------------------------------"
          echo "Memory Info:"
          free -h

      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      
      - run: echo "This job's status is ${{ job.status }}."